version: '3.8'
services:
  coin-api:
    container_name: coin-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"